# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            sujith3g
tagline:          'My Blog'
description:      'A Blog using Markdown and text editor'
url:              http://sujith3g.github.io

author:
  name:           'Sujith G'
  url:            https://github.com/sujith3g

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/poole/lanyon
