# Dependencies
markdown:         redcarpet
highlighter:         rouge

# Permalinks
permalink:        pretty

# Setup
title:            "Sujith's"
tagline:          ' Blog'
description:      'A Blog using Markdown and text editor'
url:              http://sujith3g.github.io
# url:              http://localhost:4000

author:
  name:           'Sujith G'
  url:            https://github.com/sujith3g

gems: [jekyll-paginate]
paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/sujith3g/sujith3g.github.io
